[versions]
hierynomus-license = '0.16.1'
maven-plugin-development = '1.0.3'

febit-commons = '3.4.0'
febit-devkit = '1.5.0'

embedded-postgres = '2.2.0'
spring-boot = '3.5.9'
spring-cloud = '2025.0.1'
springdoc = '2.8.15'
swagger3 = '2.2.41'
okhttp = '4.12.0'

[libraries]
febit-commons-bom = { module = 'org.febit:febit-commons-bom', version.ref = 'febit-commons' }
febit-commons-deps = { module = 'org.febit:febit-commons-dependencies', version.ref = 'febit-commons' }
spring-boot-deps = { module = 'org.springframework.boot:spring-boot-dependencies', version.ref = 'spring-boot' }
spring-cloud-deps = { module = 'org.springframework.cloud:spring-cloud-dependencies', version.ref = 'spring-cloud' }
okhttp-bom = { module = 'com.squareup.okhttp3:okhttp-bom', version.ref = 'okhttp' }

embedded-postgres = { module = 'io.zonky.test:embedded-postgres', version.ref = 'embedded-postgres' }
febit-gradle-common = { module = 'org.febit.devkit.gradle:febit-gradle-common', version.ref = 'febit-devkit' }
swagger-annotations = { module = 'io.swagger.core.v3:swagger-annotations', version.ref = 'swagger3' }

maven-core = { module = 'org.apache.maven:maven-core', version = '3.0' }
maven-plugin-api = { module = 'org.apache.maven:maven-plugin-api', version = '3.0' }
maven-plugin-annotations = { module = 'org.apache.maven.plugin-tools:maven-plugin-annotations', version = '3.5' }


[plugins]
febit-bom = { id = 'org.febit.standard-bom', version.ref = 'febit-devkit' }
febit-codegen-module = { id = 'org.febit.codegen-module', version.ref = 'febit-devkit' }
febit-java = { id = 'org.febit.standard-java', version.ref = 'febit-devkit' }
febit-maven-publish = { id = 'org.febit.standard-maven-publish', version.ref = 'febit-devkit' }

license = { id = 'com.github.hierynomus.license', version.ref = 'hierynomus-license' }
maven-plugin-development = { id = 'org.gradlex.maven-plugin-development', version.ref = 'maven-plugin-development' }
